INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (1,'ALASKA',1);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (2,'ALABAMA',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (3,'ARKANSAS',3);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (4,'AMERICAN SAMOA',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (5,'ARIZONA',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (6,'CALIFORNIA',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (7,'COLORADO',5);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (8,'N MARIANA ISLANDS',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (9,'CONNECTICUT',6);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (10,'DIST. OF COLUMBIA',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (11,'DELAWARE',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (12,'FLORIDA',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (13,'GEORGIA',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (14,'GUAM',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (15,'HAWAII',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (16,'IOWA',8);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (17,'IDAHO',5);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (18,'ILLINOIS',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (19,'INDIANA',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (20,'KANSAS',8);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (21,'KENTUCKY',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (22,'LOUISIANA',3);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (23,'MASSACHUSETTS',6);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (24,'MARYLAND',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (25,'MAINE',6);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (26,'MICHIGAN',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (27,'MINNESOTA',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (28,'MISSOURI',8);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (29,'MIDWAY ATOLL',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (30,'MISSISSIPPI',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (31,'MONTANA',5);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (32,'NORTH CAROLINA',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (33,'NORTH DAKOTA',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (34,'NEBRASKA',8);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (35,'NEW HAMPSHIRE',6);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (36,'NEW JERSEY',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (37,'NEW MEXICO',3);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (38,'NEVADA',4);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (39,'NEW YORK',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (40,'OHIO',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (41,'OKLAHOMA',3);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (42,'OREGON',5);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (43,'PENNSYLVANIA',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (44,'PUERTO RICO',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (45,'RHODE ISLAND',6);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (46,'SOUTH CAROLINA',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (47,'SOUTH DAKOTA',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (48,'TENNESSEE',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (49,'TEXAS',3);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (50,'UTAH',5);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (51,'VIRGINIA',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (52,'VIRGIN ISLANDS',2);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (53,'VERMONT',6);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (54,'WASHINGTON',5);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (55,'WISCONSIN',9);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (56,'WEST VIRGINIA',7);
INSERT INTO `superDuper_state` (id,name,faa_region_id_id) VALUES (57,'WYOMING',5);
