# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportsFAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('district_office', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('state_name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('county_state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('facility_name', models.CharField(max_length=200)),
                ('arp_latitude', models.CharField(max_length=200)),
                ('arp_latitude_s', models.CharField(max_length=200)),
                ('arp_longitude', models.CharField(max_length=200)),
                ('arp_longitude_s', models.CharField(max_length=200)),
                ('arp_elevation', models.IntegerField()),
                ('icao_identifier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AirportsFiltered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openFlightsId', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('latitude_deg', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_deg', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation_ft', models.IntegerField()),
                ('continent', models.CharField(max_length=200)),
                ('iso_country', models.CharField(max_length=200)),
                ('iso_region', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('scheduled_service', models.CharField(max_length=200)),
                ('gps_code', models.CharField(max_length=200)),
                ('iata_code', models.CharField(max_length=200)),
                ('local_code', models.CharField(max_length=200)),
                ('home_link', models.CharField(max_length=200)),
                ('wikipedia_link', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseFAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=200)),
                ('district_office', models.CharField(max_length=200)),
                ('county_state', models.CharField(max_length=200)),
                ('facility_name', models.CharField(max_length=200)),
                ('arp_latitude', models.CharField(max_length=200)),
                ('arp_latitude_s', models.CharField(max_length=200)),
                ('arp_longitude', models.CharField(max_length=200)),
                ('arp_longitude_s', models.CharField(max_length=200)),
                ('arp_elevation', models.IntegerField()),
                ('icao_identifier', models.CharField(max_length=200)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superDuper.City')),
            ],
        ),
        migrations.CreateModel(
            name='FAA_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('faa_region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superDuper.FAA_Region')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superDuper.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='county_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superDuper.County'),
        ),
    ]
