# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0002_faa_region_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faa_region',
            name='test',
        ),
    ]
