# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0003_auto_20161212_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airportsfiltered',
            name='icao',
        ),
        migrations.RemoveField(
            model_name='airportsfiltered',
            name='iso_common_name',
        ),
        migrations.AddField(
            model_name='airportsfiltered',
            name='home_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airportsfiltered',
            name='openFlightsId',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airportsfiltered',
            name='scheduled_service',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airportsfiltered',
            name='timezone',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airportsfiltered',
            name='wikipedia_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airportsfiltered',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airportsfiltered',
            name='name',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
