# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0004_auto_20161213_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportsfiltered',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
