# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0004_auto_20161215_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='county',
            new_name='county_id',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='state',
            new_name='state_id',
        ),
        migrations.RenameField(
            model_name='databasefaa',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='faa_region',
            new_name='faa_region_id',
        ),
    ]
