# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0005_auto_20161213_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportsfiltered',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
