# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0006_databasefaa_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseFAATimezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=200)),
                ('district_office', models.CharField(max_length=200)),
                ('county_state', models.CharField(max_length=200)),
                ('facility_name', models.CharField(max_length=200)),
                ('arp_latitude', models.CharField(max_length=200)),
                ('arp_latitude_s', models.CharField(max_length=200)),
                ('arp_longitude', models.CharField(max_length=200)),
                ('arp_longitude_s', models.CharField(max_length=200)),
                ('arp_elevation', models.IntegerField()),
                ('icao_identifier', models.CharField(max_length=200)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superDuper.City')),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='databasefaatimezone',
            name='timezone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superDuper.Timezone'),
        ),
    ]
