# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0006_auto_20161213_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportsFAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('location_id', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('district_office', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('state_name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('county_state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('facility_name', models.CharField(max_length=200)),
                ('arp_latitude', models.CharField(max_length=200)),
                ('arp_latitude_s', models.CharField(max_length=200)),
                ('arp_longitude', models.CharField(max_length=200)),
                ('arp_longitude_s', models.CharField(max_length=200)),
                ('arp_elevation', models.IntegerField()),
                ('icao_identifier', models.CharField(max_length=200)),
            ],
        ),
    ]
