# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0008_auto_20161219_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='county_id',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='faa_region_id',
            new_name='faa_region',
        ),
    ]
