# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0009_auto_20161219_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='icao_identifier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
