# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superDuper', '0010_auto_20161219_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='arp_elevation',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='arp_latitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='arp_latitude_s',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='arp_longitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='arp_longitude_s',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='district_office',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='site_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='databasefaatimezone',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
